"""init user model3

Revision ID: d1f8c9d93603
Revises: 530d81d9d894
Create Date: 2024-12-09 18:22:55.860937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd1f8c9d93603'
down_revision: Union[str, None] = '530d81d9d894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sysuser', sa.Column('lastTime', sa.DateTime(), nullable=True))
    op.add_column('sysuser', sa.Column('createTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sysuser', 'createTime')
    op.drop_column('sysuser', 'lastTime')
    # ### end Alembic commands ###
