"""init user model2

Revision ID: 530d81d9d894
Revises: eb4eb2ebdb3d
Create Date: 2024-12-09 17:52:09.554312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '530d81d9d894'
down_revision: Union[str, None] = 'eb4eb2ebdb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sysuser', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_column('sysuser', 'is_active')
    op.drop_column('sysuser', 'password')
    op.drop_column('sysuser', 'phoneNumber')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sysuser', sa.Column('phoneNumber', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('sysuser', sa.Column('password', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('sysuser', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('sysuser', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
